### ISSUE TITLE
puzzles for j

### ISSUE THREAD

**Issue by timm** [ai-se/softgoals#11]
- [x] when handling dependancies, do we treat them like "ands"?
- [x] when walk around a graph, if we hit a loop, is that a bug in the graph?
- [ ] table3 2014: randomized predicate for `humanJudgement`
  - selected from the unique values, not the total values

**Comment by jenhork** [comment]
Hi Tim,

For 1:
"Combinations of Links: Intentions in i\* are often the destination of more
than one type of link. This occurs when an element is the recipient of a
Dependency link and a Meansends/Decomposition link or a Contribution link.
“Hard” links (Decomposition, Means-Ends, and Dependency) are combined using
an AND of the final results of each link type. If Contribution and
Dependency links share the same destination, the result of the Dependency
links are treated as a Make contribution, considered with the other
contributions in the label bag. An example of this type can be seen in High
Quality Counseling in the Organization."
http://www.cs.toronto.edu/~jenhork/Papers/IJISMD_HorkoffYu.pdf

For 2:
For the forward procedure
"Detecting Cycles: Goal models often contain cycles, values which
indirectly contribute to themselves and may cause fluctuating values. Our
implementation of the procedure places a cap on the number of value
fluctuations possible for an intention. Experience has shown that during
manual application of the procedure the presence of cycles becomes apparent
to the evaluator after a few iterations, allowing the evaluator to select
an appropriate converging value."
http://www.cs.toronto.edu/~jenhork/Papers/IJISMD_HorkoffYu.pdf

For the backward procedure
"Restrictions on an agent-goal model. In order to produce an agent-goal
model which can be more easily translated into CNF form and to ensure the
convergence and termination of the algorithm, we place the following
restrictions on the model: ....
– The model must have no cycles, i.e., for every path in the model, ...."
http://www.cs.toronto.edu/~jenhork/Papers/ER_Horkoff.pdf

So forward procedure can handle cycles, backwards can't.  So we disallow
for cycles in the latter case.  Easiest to disallow for cycles in both
cases.  The sample models I've sent will probably have cycles.

Hope that helps,

Jennifer

**Comment by timm** [comment]
thanks @jenhork 

fyi- our goal here is a package called pyistar0 that anyone can download via (say) pip containing:
- [ ]  100s of models expressed in some high-level json/python syntax (so it autoloads generating python structs)
- [ ] a < 100 line interpreter for the forward/backwards analysis
- [ ] baseline results showing we can do cool things with the interpreter on the 100s of models

so, in the near future, i hope to be asking you to work on a large TSE article of the form of http://dl.acm.org/citation.cfm?id=2738037 which becomes the basis for 1000s of future RE papers.

**Comment by bigfatnoob** [comment]
Moved here #15

**Comment by jenhork** [comment]
Catching up with emails.  This sounds interesting, and we can discuss more
hopefully when you visit U of T on Friday.

Some initial thoughts:
the < 100 line interpreter:  I'm good with this for forward analysis, but
more skeptical for backward.  Backward analysis is a computationally hard
problem, we were using SAT and CSPs and such to solve it.  Probably you can
code something different, but I'm curious about the computational
complexity.

As you might have seen from my papers, just because you can automatically
analyze an i\* model doesn't mean that you should.   I work on models which,
in the end, must be built and interpreted by humans, so favor interactive
analysis that involves people in the process of model understanding and
decision making.  I would have a hard time trusting any results you
calculate automatically over large models.  These models are almost
sketches in a way, high-level, social models.  In my REJ'13 paper
( Comparison and Evaluation of Goal-Oriented Satisfaction Analysis
Techniques) I note that the small differences you make in goal model
interpretation makes a big difference on the overall analysis results and
resulting decisions.  Thus these models should never be used as a black box.

This is something we can also discuss:  the why? and what for?  :)

Best,

Jennifer
