### ISSUE TITLE
.OOD to models

### ISSUE THREAD

**Issue by bigfatnoob** [ai-se/softgoals#5]
.ood files used by OpenOME opens by default as an xml file. We should be able to parse it and extract the tasks(decisions) and goals/softgoals (objectives) from the xml. It can then be coupled with  https://github.com/ai-se/softgoals/blob/master/interpret.md

**Comment by timm** [comment]
what is the bughub id of your colleague? you need to @her on these emails.

t

**Comment by bigfatnoob** [comment]
@timm are you referring to Dr Horkoff ?

**Comment by timm** [comment]
no... your partner you meet tueday

**Comment by jenhork** [comment]
Hello again,

Some more thoughts and questions about parsing the Visio models.  I just
chatted with my colleague here who made a VB tool to do things with goal
models in Visio (REDEPEND http://ceur-ws.org/Vol-344/paper18.pdf).  They
didn't ever write any export function, so I don't think the code will be
very useful to you. Also, that tool and my models use different templates.
  But he reminded me that Visio does have export functions.  You can export
to an excel report, and to some other  formats.  I might check those out
before writing a parser from scratch.

OpenOME models are easier to parse, in fact there's a function in OpenOME
that saves models to something called iStarML (
http://www.upc.edu/gessi/istar/tools/istarml/), but the big counseling
models pre-date OpenOME and are in Visio.

At RE, I was chatting with Sam Suppakul (
http://dblp.uni-trier.de/pers/hd/s/Supakkul:Sam).  He's interested in using
the same large models to test out their NFR pattern work.   Of course they
would also need some sort of parser.  Would you make the parser available
along with the models in the public repository?  Or the parsed output?
Otherwise he's on his own, and I'll let him know.

Best Regards,

Jennifer

**Comment by bigfatnoob** [comment]
Dr Horkoff (@jenhork),

So I started writing a parser for the .ood files which are xml formatted files. It will be on this repo, so I think anyone should be able to use it. 
For the .vsd files, I tried exporting those files to xml, but the format of the xml differs from those of .ood files. So I might have to write another parser for that format of the xml.
I plan to finish up the parser for .ood files and then move on to the visio exported xml files.

**Comment by jenhork** [comment]
Dear George,

Great, thanks for the update.  If you complete a Visio parser, please let
me know.   What is the destination format of your parser?  Regular XML or
for some other tool?

I would also try to export from OpenOME to iStarML and see if that helps, I
had a summer student implement this is 2011:
https://se.cs.toronto.edu/trac/ome/wiki/ImportingExporting

Best,

Jennifer

**Comment by bigfatnoob** [comment]
For our experiments we use python, so our end goal is to generate a model that can be sent into our optimizers. So I was currently targeting a python model as the end point. I can additionally output it into a json format as it does not involve significant effort once I construct a python model.

**Comment by jenhork** [comment]
json would be very helpful.  We've abandoned Eclipse-based tools and are
now working on online javascript tools, so we could potentially import from
json.

Thanks again,

Jennifer
